# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook.proto',
  package='addressbook',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x61\x64\x64ressbook.proto\x12\x0b\x61\x64\x64ressbook\"[\n\x0c\x43ontactEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05phone\x18\x03 \x02(\t\x12\r\n\x05\x65mail\x18\x04 \x02(\t\x12\x13\n\x0blast_viewed\x18\x05 \x02(\t\"\x17\n\tContactID\x12\n\n\x02id\x18\x01 \x02(\x05\"\x1b\n\x0b\x43ontactName\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x1d\n\x0c\x43ontactPhone\x12\r\n\x05phone\x18\x01 \x02(\t\"\x1d\n\x0c\x43ontactEmail\x12\r\n\x05\x65mail\x18\x01 \x02(\t\">\n\x10\x43ontactEntryList\x12*\n\x07\x63ontact\x18\x01 \x03(\x0b\x32\x19.addressbook.ContactEntry')
)




_CONTACTENTRY = _descriptor.Descriptor(
  name='ContactEntry',
  full_name='addressbook.ContactEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='addressbook.ContactEntry.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='addressbook.ContactEntry.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='addressbook.ContactEntry.phone', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='addressbook.ContactEntry.email', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_viewed', full_name='addressbook.ContactEntry.last_viewed', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=125,
)


_CONTACTID = _descriptor.Descriptor(
  name='ContactID',
  full_name='addressbook.ContactID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='addressbook.ContactID.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=150,
)


_CONTACTNAME = _descriptor.Descriptor(
  name='ContactName',
  full_name='addressbook.ContactName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='addressbook.ContactName.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=179,
)


_CONTACTPHONE = _descriptor.Descriptor(
  name='ContactPhone',
  full_name='addressbook.ContactPhone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='addressbook.ContactPhone.phone', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=210,
)


_CONTACTEMAIL = _descriptor.Descriptor(
  name='ContactEmail',
  full_name='addressbook.ContactEmail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='addressbook.ContactEmail.email', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=241,
)


_CONTACTENTRYLIST = _descriptor.Descriptor(
  name='ContactEntryList',
  full_name='addressbook.ContactEntryList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contact', full_name='addressbook.ContactEntryList.contact', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=305,
)

_CONTACTENTRYLIST.fields_by_name['contact'].message_type = _CONTACTENTRY
DESCRIPTOR.message_types_by_name['ContactEntry'] = _CONTACTENTRY
DESCRIPTOR.message_types_by_name['ContactID'] = _CONTACTID
DESCRIPTOR.message_types_by_name['ContactName'] = _CONTACTNAME
DESCRIPTOR.message_types_by_name['ContactPhone'] = _CONTACTPHONE
DESCRIPTOR.message_types_by_name['ContactEmail'] = _CONTACTEMAIL
DESCRIPTOR.message_types_by_name['ContactEntryList'] = _CONTACTENTRYLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContactEntry = _reflection.GeneratedProtocolMessageType('ContactEntry', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTENTRY,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.ContactEntry)
  ))
_sym_db.RegisterMessage(ContactEntry)

ContactID = _reflection.GeneratedProtocolMessageType('ContactID', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTID,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.ContactID)
  ))
_sym_db.RegisterMessage(ContactID)

ContactName = _reflection.GeneratedProtocolMessageType('ContactName', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTNAME,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.ContactName)
  ))
_sym_db.RegisterMessage(ContactName)

ContactPhone = _reflection.GeneratedProtocolMessageType('ContactPhone', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTPHONE,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.ContactPhone)
  ))
_sym_db.RegisterMessage(ContactPhone)

ContactEmail = _reflection.GeneratedProtocolMessageType('ContactEmail', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTEMAIL,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.ContactEmail)
  ))
_sym_db.RegisterMessage(ContactEmail)

ContactEntryList = _reflection.GeneratedProtocolMessageType('ContactEntryList', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTENTRYLIST,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.ContactEntryList)
  ))
_sym_db.RegisterMessage(ContactEntryList)


# @@protoc_insertion_point(module_scope)
